services:
  #TestManagment service
  testmanagment:
    image: ${DOCKER_REGISTRY-}testmanagment
    container_name: testmanagment
    build:
      context: ./TestManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db-exam;Database=TestingStudents;User Id=sa;Password=Abc.123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5139 
    depends_on: 
      db-exam:
        condition: service_healthy
    networks:
      - internal

 #GradingManagment service
  gradingmanagment1:
    image: ${DOCKER_REGISTRY-}gradingmanagment
    container_name: gradingmanagment1
    build:
      context: ./GradingManagment
      dockerfile: Dockerfile
    environment:
      - RUN_MIGRATION=true
      - ConnectionStrings__local=Server=db-grade;Database=GradingStudents;User Id=sa;Password=Abc.123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5066
    depends_on:
      db-grade:
        condition: service_healthy
    networks:
      - internal


  gradingmanagment2:
    image: ${DOCKER_REGISTRY-}gradingmanagment
    container_name: gradingmanagment2
    build:
      context: ./GradingManagment
      dockerfile: Dockerfile
    environment:
      - RUN_MIGRATION=false
      - ConnectionStrings__local=Server=db-grade;Database=GradingStudents;User Id=sa;Password=Abc.123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5067
    depends_on:
      db-grade:
        condition: service_healthy
      
    networks:
      - internal
  
  #Api Getway and Auth service
  studentaccountmanagment:
    image: ${DOCKER_REGISTRY-}studentaccountmanagment
    container_name: studentaccountmanagment
    build:
      context: ./StudentAccountManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db-exam;Database=AuthTestingSystem;User Id=sa;Password=Abc.123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5169
    ports:
      - "5169:5169"
    depends_on:
      db-exam: 
        condition: service_healthy  
    networks:
      - internal

  #Database servers
  db-grade:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-grade
    environment:
       SA_PASSWORD: "Abc.123"
       ACCEPT_EULA: "Y"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  db-exam:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-exam
    environment:
      SA_PASSWORD: "Abc.123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      retries: 5
      interval: 2s
      timeout: 5s
      start_period: 10s
    networks:
      - internal

networks:
  internal:
    driver: bridge