services:
  testmanagment:
    image: ${DOCKER_REGISTRY-}testmanagment
    container_name: testmanagment
    build:
      context: ./TestManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db;Database=TestingStudents;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5139 
    depends_on: 
      - db
    networks:
      - internal

  gradingmanagment1:
    image: ${DOCKER_REGISTRY-}gradingmanagment
    container_name: gradingmanagment
    build:
      context: ./GradingManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db;Database=GradingStudents;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5066
    depends_on:
      - db
    networks:
      - internal


  gradingmanagment2:
    image: ${DOCKER_REGISTRY-}gradingmanagment
    container_name: gradingmanagment
    build:
      context: ./GradingManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db;Database=GradingStudents;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5067
    depends_on:
      - db
    networks:
      - internal

  studentaccountmanagment:
    image: ${DOCKER_REGISTRY-}studentaccountmanagment
    container_name: studentaccountmanagment
    build:
      context: ./StudentAccountManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db;Database=AuthTestingSystem;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5169
    ports:
      - "5169:5169"
    depends_on:
      - db
    networks:
      - internal
      - external
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
       SA_PASSWORD: "Your_strong_password123"
       ACCEPT_EULA: "Y"
    networks:
      - internal

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
