services:
  #TestManagment service
  testmanagment:
    image: josephtharwat/testmanagment
    environment:
      - ConnectionStrings__local=Server=db-exam;Database=TestingStudents;User Id=sa;Password=Abc_12345;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5139 
      - Seq__Url=http://seq:5341
    networks:
      - internal

 #GradingManagment service  
  gradingmanagment:
    image: josephtharwat/gradingmanagment
    environment:
      - ConnectionStrings__local=Server=db-grade;Database=GradingStudents;User Id=sa;Password=Abc_12345;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5066
      - Seq__Url=http://seq:5341
    networks:
      - internal
    deploy:
      replicas: 2

  #Api Getway and Auth service
  studentaccountmanagment:
    image: josephtharwat/studentaccountmanagment
    build:
      context: ./StudentAccountManagment
      dockerfile: Dockerfile
    environment:
      - ReverseProxy__Clusters__TestCreationCluster__Destinations__TestCreationService__Address=http://testmanagment:5139
      - ReverseProxy__Clusters__GradeStudentCluster__Destinations__GradeStudentService__Address=http://gradingmanagment:5066
      - ConnectionStrings__local=Server=db-exam;Database=AuthTestingSystem;User Id=sa;Password=Abc_12345;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5169
      - Seq__Url=http://seq:5341
    ports:
      - "5169:5169"
    networks:
      - internal
    

  #Database servers
  db-grade:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
       SA_PASSWORD: "Abc_12345"
       ACCEPT_EULA: "Y"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - sql-grade:/var/opt/mssql

  db-exam:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Abc_12345"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      retries: 5
      interval: 2s
      timeout: 5s
      start_period: 20s
    networks:
      - internal
    volumes:
      - sql-exam:/var/opt/mssql

  #Logger    
  seq:
    image: datalust/seq
    environment:
        - ACCEPT_EULA=Y
        - SEQ_FIRSTRUN_ADMINPASSWORD=Abc_12345
    ports:
        #- "5341:5341"
        - "5341:80" #for docker play environment
    networks:
      - internal
    volumes:
      - seq-logs:/data

volumes:
  seq-logs:
  sql-grade:
  sql-exam:

networks:
  internal:
    driver: overlay
