services:
  testmanagment:
    image: ${DOCKER_REGISTRY-}testmanagment
    container_name: testmanagment
    build:
      context: ./TestManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db;Database=TestingStudents;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5139 
    depends_on: 
      db:
        condition: service_healthy
    networks:
      - internal

  gradingmanagment1:
    image: ${DOCKER_REGISTRY-}gradingmanagment
    container_name: gradingmanagment1
    build:
      context: ./GradingManagment
      dockerfile: Dockerfile
    environment:
      - RUN_MIGRATION=true
      - ConnectionStrings__local=Server=db;Database=GradingStudents;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5066
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal


  gradingmanagment2:
    image: ${DOCKER_REGISTRY-}gradingmanagment
    container_name: gradingmanagment2
    build:
      context: ./GradingManagment
      dockerfile: Dockerfile
    environment:
      - RUN_MIGRATION=false
      - ConnectionStrings__local=Server=db;Database=GradingStudents;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5067
    depends_on:
      db:
        condition: service_healthy
      
    networks:
      - internal

  studentaccountmanagment:
    image: ${DOCKER_REGISTRY-}studentaccountmanagment
    container_name: studentaccountmanagment
    build:
      context: ./StudentAccountManagment
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__local=Server=db;Database=AuthTestingSystem;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:5169
    ports:
      - "5169:5169"
    depends_on:
      db: 
        condition: service_healthy
        
    networks:
      - internal
      - external
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
       SA_PASSWORD: "Your_strong_password123"
       ACCEPT_EULA: "Y"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
